"""
V6 PDF Report Generator — produces analyst-grade PDF reports like AWS Security Agent.

Generates a styled PDF with:
- Cover page with title, date, target
- Table of contents
- Executive summary with severity chart
- Zero trust assessment
- Detailed findings with evidence walks
- Attack chains
- Recommendations
"""
from __future__ import annotations

import json
import logging
from datetime import datetime
from pathlib import Path
from dataclasses import dataclass

logger = logging.getLogger(__name__)


def generate_pdf_report(
    report_data: dict,
    output_path: str,
    title: str = "Security Analysis Report",
) -> str:
    """
    Generate a styled PDF report from V6 scan results.

    Args:
        report_data: dict with keys: summary, findings, attack_chains, zero_trust
        output_path: where to write the PDF
        title: report title

    Returns:
        path to generated PDF
    """
    html = _build_html(report_data, title)

    # Save HTML report (always works, no system deps)
    html_path = output_path.replace(".pdf", ".html")
    Path(html_path).write_text(html)
    return html_path


def _build_html(data: dict, title: str) -> str:
    """Build the full HTML document."""
    summary = data.get("summary", {})
    findings = data.get("findings", [])
    chains = data.get("attack_chains", [])
    zero_trust = data.get("zero_trust", {})
    date = datetime.now().strftime("%B %d, %Y")
    target = summary.get("repo", "Unknown target")

    # Severity counts
    sev_dist = summary.get("severity_distribution", {})
    critical = sev_dist.get("CRITICAL", 0)
    high = sev_dist.get("HIGH", 0)
    medium = sev_dist.get("MEDIUM", 0)
    low = sev_dist.get("LOW", 0)
    total = summary.get("total_findings", len(findings))

    findings_html = _render_findings(findings)
    chains_html = _render_chains(chains)
    zt_html = _render_zero_trust(zero_trust)

    return f"""<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
{_get_styles()}
</style>
</head>
<body>

<!-- Cover Page -->
<div class="cover">
    <h1>{title}</h1>
    <div class="cover-meta">
        <p class="target">{target}</p>
        <p class="date">{date}</p>
    </div>
</div>

<!-- Navigation -->
<nav class="toc">
    <h3>Contents</h3>
    <ul>
        <li><a href="#executive-summary">Executive Summary</a></li>
        <li><a href="#zero-trust">Zero Trust Assessment</a></li>
        <li><a href="#findings">Findings ({total})</a></li>
        <li><a href="#attack-chains">Attack Chains</a></li>
    </ul>
</nav>

<h2 id="executive-summary">Executive Summary</h2>
<p>This security analysis identified <strong>{total} findings</strong>:
{critical} critical, {high} high, {medium} medium, {low} low severity issues.</p>

<div class="severity-chart">
    <div class="sev-bar critical" style="width: {max(critical * 40, 5)}px">{critical}</div>
    <div class="sev-bar high" style="width: {max(high * 40, 5)}px">{high}</div>
    <div class="sev-bar medium" style="width: {max(medium * 40, 5)}px">{medium}</div>
    <div class="sev-bar low" style="width: {max(low * 40, 5)}px">{low}</div>
</div>
<div class="sev-legend">
    <span class="legend-item critical">■ Critical</span>
    <span class="legend-item high">■ High</span>
    <span class="legend-item medium">■ Medium</span>
    <span class="legend-item low">■ Low</span>
</div>

<h3>Key Metrics</h3>
<table class="metrics">
    <tr><td>Z3 Formal Proofs</td><td>{summary.get('z3_findings', 0)}</td></tr>
    <tr><td>Zero Trust Uncontained</td><td>{summary.get('zero_trust_uncontained', 0)} resources</td></tr>
    <tr><td>Lateral Movement Paths</td><td>{summary.get('lateral_paths', 0)}</td></tr>
    <tr><td>Attack Chains</td><td>{summary.get('attack_chains', 0)} ({len([c for c in chains if c.get('composite_severity') == 'CRITICAL'])} critical)</td></tr>
</table>

<!-- Zero Trust Assessment -->
{zt_html}

<!-- Findings -->
<h2 id="findings">Detailed Findings</h2>
{findings_html}

<!-- Attack Chains -->
<h2 id="attack-chains">Attack Chains</h2>
{chains_html}

<!-- Footer -->
<div class="footer">
    <p>Generated by Security Agent V6 — {date}</p>
</div>

</body>
</html>"""


def _render_findings(findings: list[dict]) -> str:
    """Render all findings as HTML."""
    html_parts = []
    for i, f in enumerate(findings, 1):
        severity = f.get("severity", "MEDIUM")
        sev_class = severity.lower()
        evidence = f.get("evidence", "")
        verified = f.get("verified", [])
        unverified = f.get("could_not_verify", [])
        fix = f.get("suggested_fix", "")
        locations = f.get("code_locations", [])

        finding_id = f"finding-{i}"
        html_parts.append(f"""
<div class="finding" id="{finding_id}">
    <h3><a href="#{finding_id}">Finding {i}</a>: {f.get('title', 'Untitled')}</h3>
    <div class="finding-meta">
        <span class="severity-badge {sev_class}">{severity}</span>
        <span class="meta-item">Confidence: {f.get('confidence', 'HIGH')}</span>
        <span class="meta-item">Risk: {f.get('risk_type', '')}</span>
        {f'<span class="meta-item">CWE: {f.get("cwe", "")}</span>' if f.get('cwe') else ''}
    </div>

    <h4>Description</h4>
    <p>{f.get('description', '')}</p>

    {'<details open><summary><strong>Evidence Walk</strong></summary><pre class="evidence">' + evidence + '</pre></details>' if evidence else ''}

    {'<h4>Verified</h4><ul>' + ''.join(f'<li>{v}</li>' for v in verified) + '</ul>' if verified else ''}

    {'<h4>Could Not Verify</h4><ul>' + ''.join(f'<li>{v}</li>' for v in unverified) + '</ul>' if unverified else ''}

    {'<h4>Code Locations</h4><ul>' + ''.join(f'<li><code>{l}</code></li>' for l in locations) + '</ul>' if locations else ''}

    {'<h4>Suggested Fix</h4><div class="fix">' + fix + '</div>' if fix else ''}
</div>
<hr>
""")
    return "\n".join(html_parts)


def _render_chains(chains: list[dict]) -> str:
    """Render attack chains as HTML."""
    if not chains:
        return "<p>No attack chains identified.</p>"

    html_parts = []
    for chain in chains:
        steps_html = ""
        for step in chain.get("steps", []):
            steps_html += f'<li>[{step.get("severity", "")}] {step.get("title", "")}</li>'

        html_parts.append(f"""
<div class="chain">
    <h3>{chain.get('title', 'Attack Chain')}</h3>
    <span class="severity-badge {chain.get('composite_severity', 'HIGH').lower()}">{chain.get('composite_severity', '')}</span>
    <ol>{steps_html}</ol>
    <p class="narrative">{chain.get('narrative', '')[:500]}</p>
</div>
""")
    return "\n".join(html_parts)


def _render_zero_trust(zt: dict) -> str:
    """Render zero trust assessment as HTML."""
    if not zt:
        return ""

    posture = zt.get("posture", "NOT_ASSESSED")
    uncontained = zt.get("summary", {}).get("uncontained", 0)
    total = zt.get("summary", {}).get("total_compute_resources", 0)
    blast_radii = zt.get("blast_radii", {})
    lateral = zt.get("lateral_paths", [])

    posture_class = "critical" if "VIOLATED" in posture else "medium" if "PARTIAL" in posture else "low"

    br_rows = ""
    for rid, br in blast_radii.items():
        if br.get("status") == "UNCONTAINED":
            caps = br.get("capabilities", {})
            cap_list = [k for k, v in caps.items() if v]
            br_rows += f"""
            <tr class="uncontained">
                <td>{br.get('role', rid)}</td>
                <td>{'Yes' if br.get('internet_facing') else 'No'}</td>
                <td>{br.get('auth', 'unknown')}</td>
                <td>{', '.join(cap_list)}</td>
            </tr>"""

    return f"""
<h2 id="zero-trust">Zero Trust Assessment</h2>
<div class="zt-posture">
    <span class="severity-badge {posture_class}">Posture: {posture}</span>
    <p>Uncontained resources: {uncontained} / {total}</p>
</div>

<h3>Uncontained Resources (Blast Radius)</h3>
<table class="zt-table">
    <thead><tr><th>Role</th><th>Internet-Facing</th><th>Auth</th><th>Capabilities</th></tr></thead>
    <tbody>{br_rows}</tbody>
</table>

<h3>Lateral Movement</h3>
<p>{len(lateral)} lateral movement paths identified via shared data stores.</p>
"""


def _get_styles() -> str:
    """CSS styles for the report."""
    return """
body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
    font-size: 11pt;
    line-height: 1.5;
    color: #1a1a1a;
    max-width: 800px;
    margin: 0 auto;
    padding: 40px;
}
.cover {
    text-align: center;
    padding: 200px 0 100px;
}
.cover h1 {
    font-size: 28pt;
    color: #1a1a1a;
    margin-bottom: 40px;
}
.cover-meta { color: #666; font-size: 14pt; }
.page-break { page-break-before: always; }
h2 { color: #1a1a1a; border-bottom: 2px solid #e0e0e0; padding-bottom: 8px; margin-top: 40px; }
h3 { color: #333; margin-top: 24px; }
h4 { color: #555; margin-top: 16px; margin-bottom: 8px; }

.severity-badge {
    display: inline-block;
    padding: 3px 10px;
    border-radius: 4px;
    font-size: 10pt;
    font-weight: bold;
    color: white;
}
.severity-badge.critical { background: #d32f2f; }
.severity-badge.high { background: #f57c00; }
.severity-badge.medium { background: #fbc02d; color: #333; }
.severity-badge.low { background: #388e3c; }

.severity-chart { margin: 20px 0; display: flex; gap: 4px; align-items: center; }
.sev-bar { height: 30px; display: flex; align-items: center; justify-content: center;
           color: white; font-weight: bold; border-radius: 4px; min-width: 30px; }
.sev-bar.critical { background: #d32f2f; }
.sev-bar.high { background: #f57c00; }
.sev-bar.medium { background: #fbc02d; color: #333; }
.sev-bar.low { background: #388e3c; }
.sev-legend { margin: 8px 0 24px; }
.legend-item { margin-right: 16px; font-size: 10pt; }
.legend-item.critical { color: #d32f2f; }
.legend-item.high { color: #f57c00; }
.legend-item.medium { color: #fbc02d; }
.legend-item.low { color: #388e3c; }

.metrics { border-collapse: collapse; margin: 16px 0; }
.metrics td { padding: 8px 16px; border: 1px solid #e0e0e0; }
.metrics td:first-child { font-weight: bold; background: #f5f5f5; }

.finding { margin: 24px 0; }
.finding-meta { margin: 8px 0 16px; }
.meta-item { margin-left: 12px; font-size: 10pt; color: #666; }

pre.evidence {
    background: #f8f8f8;
    border: 1px solid #e0e0e0;
    border-radius: 4px;
    padding: 12px;
    font-size: 9pt;
    line-height: 1.4;
    overflow-x: auto;
    white-space: pre-wrap;
}
.fix { background: #f0f8f0; border: 1px solid #c8e6c9; border-radius: 4px; padding: 12px; font-size: 10pt; }

.chain { margin: 20px 0; padding: 16px; background: #fff8f0; border: 1px solid #ffe0b2; border-radius: 4px; }
.chain ol { margin: 8px 0; }
.narrative { font-size: 10pt; color: #555; margin-top: 8px; }

.zt-posture { margin: 16px 0; }
.zt-table { border-collapse: collapse; width: 100%; margin: 16px 0; font-size: 10pt; }
.zt-table th, .zt-table td { padding: 8px; border: 1px solid #e0e0e0; text-align: left; }
.zt-table thead { background: #f5f5f5; }
.zt-table tr.uncontained { background: #fff3f0; }

.footer { margin-top: 60px; padding-top: 20px; border-top: 1px solid #e0e0e0;
          font-size: 9pt; color: #999; text-align: center; }

hr { border: none; border-top: 1px solid #e8e8e8; margin: 32px 0; }
code { background: #f0f0f0; padding: 2px 6px; border-radius: 3px; font-size: 9pt; }
ul { padding-left: 20px; }
li { margin: 4px 0; }
a { color: #1565c0; text-decoration: none; }
a:hover { text-decoration: underline; }

nav.toc { background: #f8f8f8; border: 1px solid #e0e0e0; border-radius: 6px;
           padding: 16px 24px; margin: 24px 0; }
nav.toc h3 { margin: 0 0 8px; font-size: 12pt; }
nav.toc ul { list-style: none; padding: 0; }
nav.toc li { margin: 4px 0; }
nav.toc a { font-size: 11pt; }

details { margin: 8px 0; }
details summary { cursor: pointer; font-size: 10pt; color: #333; }
details summary:hover { color: #1565c0; }

.finding h3 a { color: inherit; }
.finding h3 a:hover { color: #1565c0; }

@media print {
    .toc { page-break-after: always; }
    .finding { page-break-inside: avoid; }
}
"""
